---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-service-account-role
  namespace: default
rules:
- apiGroups: [carto.run]
  resources: ['workloads']
  verbs: ['*']
- apiGroups: [""]
  resources: ['configmaps']
  verbs: ['*']
- apiGroups: ["tanzu.vmware.com"]
  resources: ['*']
  verbs: ['*']
- apiGroups: ["projectcontour.io"]
  resources: ['*']
  verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-service-account-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-service-account-role
subjects:
  - kind: ServiceAccount
    name: gitops-service-account
    namespace: default
