apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: products-gateway-route
spec:
  service:
    name: products
  routes:
  - predicates:
      - Path=/products/**
    order: 1
    filters:
      - StripPrefix=1
      - PrefixPath=/products-microservice/products
    uri: http://products-default.tap.yuga.ga
  - predicates:
      - Path=/products/details/sku/**
    order: 0
    filters:
      - StripPrefix=3
      - PrefixPath=/products-microservice/product
    uri: http://products-default.tap.yuga.ga


