---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: yugastore-frontend
  name: frontend
spec:
  params:
    - name: clusterBuilder
      value: full
  build:
    env:
    - name: BP_WEB_SERVER
      value: nginx
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER_ROOT
      value: build
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/yogendra/yugastore-k8s
    subPath: "src/frontend"
