apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: yugastore-gitops-workload-deployer
  namespace: default
spec:
  serviceAccountName: gitops-service-account
  fetch:
  - git:
      url: https://github.com/yogendra/yugastore-k8s
      ref: origin/master
      subPath: tap/env/west-2/workloads
  template:
  - ytt: {}
  deploy:
  - kapp: {}

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: yugastore-gitops-routes-deployer
  namespace: default
spec:
  serviceAccountName: gitops-service-account
  fetch:
  - git:
      url: https://github.com/yogendra/yugastore-k8s
      ref: origin/master
      subPath: tap/env/west-2/scg-routes
  template:
  - ytt: {}
  deploy:
  - kapp: {}
