---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
  name: cart
spec:
  env:
  - name: "EUREKA_URI"
    value: "http://eureka-default.gkelabeast.tap.fynesy.com/eureka"
  - name: "DB_HOSTNAME"
    value: "yb-tservers.yb-demo-us-east1-b.svc.cluster.local"
  - name: "spring.datasource.url"
    value: "jdbc:postgresql://yb-tservers.yb-demo-us-east1-b.svc.cluster.local:5433/yugabyte"
  build: 
    env: 
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/tfynes-pivotal/yugastore-k8s
    subPath: "src/cart"
