---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: yugastore
  name: eureka
spec:
  env:
  #- name: "yugabyte.sql.datasource.url"
  #  value: "yugabyte.sql.datasource.url: jdbc:postgresql://yb-tservers.yb-demo.svc.cluster.local:5433/yugabyte"
  build: 
    env: 
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/tfynes-pivotal/yugastore-k8s
    subPath: src/eureka-server-local
