spring:
  application:
    name: checkout-microservice
    jpa:
      database: yugabyte
      hibernate:
        ddl-auto: none
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
    data:
      jpa:
        repositories:
          enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:127.0.0.1}:5433/yugabyte
    username: yugabyte
    password: yugabyte
server:
  port: 8086
  storenum: ${STORENUM:99}
logging:
  level:
    root: info
security:
  basic:
    enabled: false


